apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  labels:
    type: webapp
spec:
  template:
   spec:
     containers:
     - name: busybox
       image: busybox
       command: [ "echo", "hello world" ]
     restartPolicy: Never
