apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
